2025-04-29 08:07:49,314 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,373 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,425 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,458 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,487 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,520 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,547 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,593 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,609 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:08:39,624 - KitchnSpy - INFO - Application started
2025-04-29 08:08:44,661 - KitchnSpy - INFO - Request started | GET /docs
2025-04-29 08:08:44,664 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.003s
2025-04-29 08:08:44,998 - KitchnSpy - INFO - Request started | GET /openapi.json
2025-04-29 08:08:45,011 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.013s
2025-04-29 08:09:03,795 - KitchnSpy - INFO - Request started | GET /api/v1/products/
2025-04-29 08:09:03,801 - KitchnSpy - ERROR - Exception | 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 104, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\infra\middleware.py", line 32, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\routers\products.py", line 22, in get_all_products
    return products_crud.find_all_products()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 68, in find_all_products
    return self.serialize_documents(products)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 24, in serialize_documents
    return [self.util.convert_objectid_to_str(doc) for doc in documents if doc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-04-29 08:09:03,914 - KitchnSpy - ERROR - Unhandled exception | 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 104, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\infra\middleware.py", line 32, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\routers\products.py", line 22, in get_all_products
    return products_crud.find_all_products()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 68, in find_all_products
    return self.serialize_documents(products)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 24, in serialize_documents
    return [self.util.convert_objectid_to_str(doc) for doc in documents if doc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-04-29 08:11:53,250 - KitchnSpy - INFO - Request started | GET /docs
2025-04-29 08:11:53,251 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.000s
2025-04-29 08:11:53,594 - KitchnSpy - INFO - Request started | GET /openapi.json
2025-04-29 08:11:53,595 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.001s
2025-04-29 08:11:57,350 - KitchnSpy - INFO - Request started | GET /api/v1/products/
2025-04-29 08:11:57,351 - KitchnSpy - ERROR - Exception | 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 104, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\infra\middleware.py", line 32, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\routers\products.py", line 22, in get_all_products
    return products_crud.find_all_products()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 68, in find_all_products
    """Find all products in the database, sorted by product name."""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 24, in serialize_documents
    """Convert ObjectId to str in a list of documents."""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-04-29 08:11:57,358 - KitchnSpy - ERROR - Unhandled exception | 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 104, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\infra\middleware.py", line 32, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\routers\products.py", line 22, in get_all_products
    return products_crud.find_all_products()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 68, in find_all_products
    """Find all products in the database, sorted by product name."""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 24, in serialize_documents
    """Convert ObjectId to str in a list of documents."""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-04-29 08:12:34,597 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,660 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,705 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,752 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,798 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,835 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,893 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,928 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:12:34,939 - KitchnSpy - INFO - Application started
2025-04-29 08:12:47,223 - KitchnSpy - INFO - Request started | GET /docs
2025-04-29 08:12:47,226 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.003s
2025-04-29 08:12:47,359 - KitchnSpy - INFO - Request started | GET /openapi.json
2025-04-29 08:12:47,366 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.008s
2025-04-29 08:12:52,007 - KitchnSpy - INFO - Request started | GET /api/v1/products/
2025-04-29 08:12:52,009 - KitchnSpy - ERROR - Exception | object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 104, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\infra\middleware.py", line 32, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\routers\products.py", line 22, in get_all_products
    return products_crud.find_all_products()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 70, in find_all_products
    return self.serialize_documents(products)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 25, in serialize_documents
    if len(documents) > 0:
       ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2025-04-29 08:12:52,030 - KitchnSpy - ERROR - Unhandled exception | object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\streams\memory.py", line 104, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\infra\middleware.py", line 32, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 163, in call_next
    raise app_exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\routers\products.py", line 22, in get_all_products
    return products_crud.find_all_products()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 70, in find_all_products
    return self.serialize_documents(products)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\KitchnSpy\app\crud\products.py", line 25, in serialize_documents
    if len(documents) > 0:
       ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2025-04-29 08:13:07,541 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,585 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,623 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,683 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,724 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,759 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,786 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,835 - KitchnSpy - INFO - MongoDB connection established successfully
2025-04-29 08:13:07,857 - KitchnSpy - INFO - Application started
2025-04-29 08:13:07,935 - KitchnSpy - INFO - Request started | GET /docs
2025-04-29 08:13:07,936 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.001s
2025-04-29 08:13:08,016 - KitchnSpy - INFO - Request started | GET /openapi.json
2025-04-29 08:13:08,032 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.015s
2025-04-29 08:13:11,496 - KitchnSpy - INFO - Request started | GET /docs
2025-04-29 08:13:11,497 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.001s
2025-04-29 08:13:11,563 - KitchnSpy - INFO - Request started | GET /openapi.json
2025-04-29 08:13:11,564 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.000s
2025-04-29 08:13:16,046 - KitchnSpy - INFO - Request started | GET /api/v1/products/
2025-04-29 08:13:16,049 - KitchnSpy - INFO - Request completed | Status: 200 | Time: 0.003s
